#!/usr/bin/env python3
"""
Formal promotion audit for Layer 5:
district-specific residual uncertainty.

Uses leakage-safe leave-one-cycle-out probabilities generated by
run_house_district_uncertainty_sensitivity.py.

Compares:
    Layer 4: constant 6.5-point total uncertainty
    Layer 5: district-specific uncertainty multipliers

Layer 5 does not change point margins, so margin MAE, RMSE, bias, and
margin-based winner accuracy are expected to remain identical.
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd


ROOT = Path(__file__).resolve().parents[3]

INPUT_DIR = (
    ROOT
    / "historical"
    / "house"
    / "backtests"
    / "outputs"
    / "district_uncertainty_sensitivity"
)

DETAIL_PATH = (
    INPUT_DIR
    / "house_district_uncertainty_best_detail.csv"
)

SELECTION_PATH = (
    INPUT_DIR
    / "house_district_uncertainty_selection.csv"
)

OUTPUT_DIR = (
    ROOT
    / "historical"
    / "house"
    / "backtests"
    / "outputs"
    / "layer5_promotion_audit"
)

CYCLE_AUDIT_PATH = (
    OUTPUT_DIR
    / "house_layer5_cycle_audit.csv"
)

POOLED_AUDIT_PATH = (
    OUTPUT_DIR
    / "house_layer5_pooled_audit.csv"
)

CALIBRATION_PATH = (
    OUTPUT_DIR
    / "house_layer5_calibration_bins.csv"
)

DECISION_PATH = (
    OUTPUT_DIR
    / "house_layer5_promotion_decision.csv"
)

EPSILON = 1e-12
CALIBRATION_BINS = np.linspace(0.0, 1.0, 11)


def binary_log_loss(
    actual: np.ndarray,
    probability: np.ndarray,
) -> float:
    probability = np.clip(
        probability,
        EPSILON,
        1.0 - EPSILON,
    )

    return float(
        -np.mean(
            actual * np.log(probability)
            + (1.0 - actual)
            * np.log(1.0 - probability)
        )
    )


def expected_calibration_error(
    actual: np.ndarray,
    probability: np.ndarray,
) -> float:
    bin_ids = np.digitize(
        probability,
        CALIBRATION_BINS[1:-1],
        right=False,
    )

    total = len(actual)
    ece = 0.0

    for bin_id in range(10):
        mask = bin_ids == bin_id
        count = int(mask.sum())

        if count == 0:
            continue

        predicted = float(probability[mask].mean())
        observed = float(actual[mask].mean())

        ece += (
            count / total
        ) * abs(predicted - observed)

    return float(ece)


def interval_coverage(
    actual_margin: np.ndarray,
    predicted_margin: np.ndarray,
    uncertainty_sd: np.ndarray,
    z_value: float,
) -> float:
    lower = predicted_margin - z_value * uncertainty_sd
    upper = predicted_margin + z_value * uncertainty_sd

    return float(
        np.mean(
            (actual_margin >= lower)
            & (actual_margin <= upper)
        )
    )


def evaluate_subset(
    frame: pd.DataFrame,
    cycle_label: str,
) -> dict[str, float | int | str]:
    actual_win = frame[
        "actual_dem_win"
    ].to_numpy(dtype=float)

    baseline_probability = frame[
        "baseline_dem_win_probability"
    ].to_numpy(dtype=float)

    layer5_probability = frame[
        "adjusted_dem_win_probability"
    ].to_numpy(dtype=float)

    predicted_margin = frame[
        "model_margin_dem"
    ].to_numpy(dtype=float)

    actual_margin = frame[
        "actual_dem_margin"
    ].to_numpy(dtype=float)

    margin_error = (
        predicted_margin - actual_margin
    )

    baseline_sd = frame[
        "baseline_total_sd"
    ].to_numpy(dtype=float)

    layer5_sd = frame[
        "adjusted_total_error_sd"
    ].to_numpy(dtype=float)

    actual_dem_seats = float(actual_win.sum())

    baseline_expected_dem_seats = float(
        baseline_probability.sum()
    )

    layer5_expected_dem_seats = float(
        layer5_probability.sum()
    )

    baseline_brier = float(
        np.mean(
            np.square(
                baseline_probability - actual_win
            )
        )
    )

    layer5_brier = float(
        np.mean(
            np.square(
                layer5_probability - actual_win
            )
        )
    )

    baseline_log_loss = binary_log_loss(
        actual_win,
        baseline_probability,
    )

    layer5_log_loss = binary_log_loss(
        actual_win,
        layer5_probability,
    )

    baseline_ece = expected_calibration_error(
        actual_win,
        baseline_probability,
    )

    layer5_ece = expected_calibration_error(
        actual_win,
        layer5_probability,
    )

    predicted_winner = (
        predicted_margin > 0
    ).astype(float)

    winner_accuracy = float(
        np.mean(
            predicted_winner == actual_win
        )
    )

    return {
        "cycle": cycle_label,
        "scored_races": int(len(frame)),
        "actual_dem_seats": actual_dem_seats,
        "baseline_expected_dem_seats": (
            baseline_expected_dem_seats
        ),
        "layer5_expected_dem_seats": (
            layer5_expected_dem_seats
        ),
        "baseline_seat_error": (
            baseline_expected_dem_seats
            - actual_dem_seats
        ),
        "layer5_seat_error": (
            layer5_expected_dem_seats
            - actual_dem_seats
        ),
        "baseline_abs_seat_error": abs(
            baseline_expected_dem_seats
            - actual_dem_seats
        ),
        "layer5_abs_seat_error": abs(
            layer5_expected_dem_seats
            - actual_dem_seats
        ),
        "abs_seat_error_change": (
            abs(
                layer5_expected_dem_seats
                - actual_dem_seats
            )
            - abs(
                baseline_expected_dem_seats
                - actual_dem_seats
            )
        ),
        "margin_mae": float(
            np.mean(np.abs(margin_error))
        ),
        "margin_rmse": float(
            np.sqrt(
                np.mean(
                    np.square(margin_error)
                )
            )
        ),
        "margin_bias_dem": float(
            np.mean(margin_error)
        ),
        "winner_accuracy": winner_accuracy,
        "baseline_brier": baseline_brier,
        "layer5_brier": layer5_brier,
        "brier_change": (
            layer5_brier - baseline_brier
        ),
        "baseline_log_loss": baseline_log_loss,
        "layer5_log_loss": layer5_log_loss,
        "log_loss_change": (
            layer5_log_loss
            - baseline_log_loss
        ),
        "baseline_ece": baseline_ece,
        "layer5_ece": layer5_ece,
        "ece_change": (
            layer5_ece - baseline_ece
        ),
        "baseline_50_coverage": interval_coverage(
            actual_margin,
            predicted_margin,
            baseline_sd,
            0.67448975,
        ),
        "layer5_50_coverage": interval_coverage(
            actual_margin,
            predicted_margin,
            layer5_sd,
            0.67448975,
        ),
        "baseline_80_coverage": interval_coverage(
            actual_margin,
            predicted_margin,
            baseline_sd,
            1.28155157,
        ),
        "layer5_80_coverage": interval_coverage(
            actual_margin,
            predicted_margin,
            layer5_sd,
            1.28155157,
        ),
        "baseline_95_coverage": interval_coverage(
            actual_margin,
            predicted_margin,
            baseline_sd,
            1.95996398,
        ),
        "layer5_95_coverage": interval_coverage(
            actual_margin,
            predicted_margin,
            layer5_sd,
            1.95996398,
        ),
        "mean_layer5_multiplier": float(
            frame[
                "district_uncertainty_multiplier"
            ].mean()
        ),
        "mean_layer5_total_sd": float(
            frame[
                "adjusted_total_error_sd"
            ].mean()
        ),
    }


def build_calibration_bins(
    frame: pd.DataFrame,
) -> pd.DataFrame:
    rows: list[dict[str, float | int | str]] = []

    actual = frame[
        "actual_dem_win"
    ].to_numpy(dtype=float)

    models = {
        "Layer 4": frame[
            "baseline_dem_win_probability"
        ].to_numpy(dtype=float),
        "Layer 5": frame[
            "adjusted_dem_win_probability"
        ].to_numpy(dtype=float),
    }

    for model_name, probability in models.items():
        bin_ids = np.digitize(
            probability,
            CALIBRATION_BINS[1:-1],
            right=False,
        )

        for bin_id in range(10):
            mask = bin_ids == bin_id
            count = int(mask.sum())

            if count == 0:
                continue

            predicted = float(
                probability[mask].mean()
            )

            observed = float(
                actual[mask].mean()
            )

            rows.append(
                {
                    "model": model_name,
                    "bin_number": bin_id + 1,
                    "bin_lower": float(
                        CALIBRATION_BINS[bin_id]
                    ),
                    "bin_upper": float(
                        CALIBRATION_BINS[
                            bin_id + 1
                        ]
                    ),
                    "races": count,
                    "mean_predicted_probability": (
                        predicted
                    ),
                    "observed_dem_win_rate": (
                        observed
                    ),
                    "calibration_gap": (
                        predicted - observed
                    ),
                    "absolute_calibration_gap": abs(
                        predicted - observed
                    ),
                }
            )

    return pd.DataFrame(rows)


def main() -> None:
    if not DETAIL_PATH.exists():
        raise FileNotFoundError(
            f"Missing sensitivity detail: {DETAIL_PATH}"
        )

    if not SELECTION_PATH.exists():
        raise FileNotFoundError(
            f"Missing selected configuration: "
            f"{SELECTION_PATH}"
        )

    detail = pd.read_csv(DETAIL_PATH)
    selection = pd.read_csv(SELECTION_PATH)

    required = [
        "held_out_cycle",
        "district_id",
        "model_margin_dem",
        "actual_dem_margin",
        "actual_dem_win",
        "baseline_total_sd",
        "adjusted_total_error_sd",
        "baseline_dem_win_probability",
        "adjusted_dem_win_probability",
        "district_uncertainty_multiplier",
    ]

    missing = [
        column
        for column in required
        if column not in detail.columns
    ]

    if missing:
        raise ValueError(
            f"Detail file missing columns: {missing}"
        )

    numeric_columns = [
        "held_out_cycle",
        "model_margin_dem",
        "actual_dem_margin",
        "actual_dem_win",
        "baseline_total_sd",
        "adjusted_total_error_sd",
        "baseline_dem_win_probability",
        "adjusted_dem_win_probability",
        "district_uncertainty_multiplier",
    ]

    for column in numeric_columns:
        detail[column] = pd.to_numeric(
            detail[column],
            errors="coerce",
        )

    detail = detail.dropna(
        subset=numeric_columns
    ).copy()

    detail["held_out_cycle"] = (
        detail["held_out_cycle"].astype(int)
    )

    cycle_rows = []

    for cycle in sorted(
        detail["held_out_cycle"].unique()
    ):
        subset = detail.loc[
            detail["held_out_cycle"] == cycle
        ].copy()

        cycle_rows.append(
            evaluate_subset(
                subset,
                str(cycle),
            )
        )

    pooled_result = evaluate_subset(
        detail,
        "Pooled",
    )

    cycle_audit = pd.DataFrame(cycle_rows)
    pooled_audit = pd.DataFrame(
        [pooled_result]
    )

    calibration = build_calibration_bins(
        detail
    )

    cycles_brier_improved = int(
        (
            cycle_audit["brier_change"] < 0
        ).sum()
    )

    cycles_log_loss_improved = int(
        (
            cycle_audit["log_loss_change"] < 0
        ).sum()
    )

    cycles_seat_error_improved = int(
        (
            cycle_audit[
                "abs_seat_error_change"
            ] < 0
        ).sum()
    )

    pooled_brier_improved = bool(
        pooled_result["brier_change"] < 0
    )

    pooled_log_loss_improved = bool(
        pooled_result["log_loss_change"] < 0
    )

    # Conservative promotion rule:
    # 1. Pooled Brier does not worsen.
    # 2. Pooled log loss improves.
    # 3. At least half of cycles improve log loss.
    # 4. No point-margin outputs change.
    promotion_passes = bool(
        pooled_result["brier_change"] <= 0
        and pooled_result[
            "log_loss_change"
        ] < 0
        and cycles_log_loss_improved >= 2
    )

    decision = pd.DataFrame(
        [
            {
                "selected_district_component_sd": (
                    selection.iloc[0][
                        "selected_district_component_sd"
                    ]
                ),
                "selected_shrinkage_strength": (
                    selection.iloc[0][
                        "selected_shrinkage_strength"
                    ]
                ),
                "selected_multiplier_floor": (
                    selection.iloc[0][
                        "selected_multiplier_floor"
                    ]
                ),
                "selected_multiplier_ceiling": (
                    selection.iloc[0][
                        "selected_multiplier_ceiling"
                    ]
                ),
                "pooled_brier_improved": (
                    pooled_brier_improved
                ),
                "pooled_log_loss_improved": (
                    pooled_log_loss_improved
                ),
                "cycles_brier_improved": (
                    cycles_brier_improved
                ),
                "cycles_log_loss_improved": (
                    cycles_log_loss_improved
                ),
                "cycles_seat_error_improved": (
                    cycles_seat_error_improved
                ),
                "total_cycles": int(
                    len(cycle_audit)
                ),
                "pooled_brier_change": (
                    pooled_result[
                        "brier_change"
                    ]
                ),
                "pooled_log_loss_change": (
                    pooled_result[
                        "log_loss_change"
                    ]
                ),
                "pooled_ece_change": (
                    pooled_result[
                        "ece_change"
                    ]
                ),
                "pooled_abs_seat_error_change": (
                    pooled_result[
                        "abs_seat_error_change"
                    ]
                ),
                "promotion_rule_passes": (
                    promotion_passes
                ),
                "promotion_decision": (
                    "KEEP LAYER 5"
                    if promotion_passes
                    else "REVERT OR RETUNE LAYER 5"
                ),
                "interpretation": (
                    "Layer 5 changes probability "
                    "dispersion only; point margins "
                    "and winner calls remain unchanged."
                ),
            }
        ]
    )

    OUTPUT_DIR.mkdir(
        parents=True,
        exist_ok=True,
    )

    cycle_audit.to_csv(
        CYCLE_AUDIT_PATH,
        index=False,
    )

    pooled_audit.to_csv(
        POOLED_AUDIT_PATH,
        index=False,
    )

    calibration.to_csv(
        CALIBRATION_PATH,
        index=False,
    )

    decision.to_csv(
        DECISION_PATH,
        index=False,
    )

    print("House Layer 5 promotion audit")
    print("-----------------------------")

    print("\nCycle-by-cycle results:")
    display_columns = [
        "cycle",
        "scored_races",
        "actual_dem_seats",
        "baseline_expected_dem_seats",
        "layer5_expected_dem_seats",
        "baseline_abs_seat_error",
        "layer5_abs_seat_error",
        "brier_change",
        "log_loss_change",
        "ece_change",
        "mean_layer5_multiplier",
    ]

    print(
        cycle_audit[
            display_columns
        ].to_string(index=False)
    )

    print("\nPooled results:")
    pooled_columns = [
        "scored_races",
        "margin_mae",
        "margin_rmse",
        "margin_bias_dem",
        "winner_accuracy",
        "baseline_brier",
        "layer5_brier",
        "brier_change",
        "baseline_log_loss",
        "layer5_log_loss",
        "log_loss_change",
        "baseline_ece",
        "layer5_ece",
        "ece_change",
        "baseline_abs_seat_error",
        "layer5_abs_seat_error",
        "abs_seat_error_change",
    ]

    print(
        pooled_audit[
            pooled_columns
        ].to_string(index=False)
    )

    print("\nCoverage:")
    coverage_columns = [
        "baseline_50_coverage",
        "layer5_50_coverage",
        "baseline_80_coverage",
        "layer5_80_coverage",
        "baseline_95_coverage",
        "layer5_95_coverage",
    ]

    print(
        pooled_audit[
            coverage_columns
        ].to_string(index=False)
    )

    print("\nPromotion decision:")
    print(
        decision.to_string(index=False)
    )

    print(f"\nWrote: {CYCLE_AUDIT_PATH}")
    print(f"Wrote: {POOLED_AUDIT_PATH}")
    print(f"Wrote: {CALIBRATION_PATH}")
    print(f"Wrote: {DECISION_PATH}")


if __name__ == "__main__":
    main()
