from pathlib import Path
import pandas as pd
import streamlit as st

POLL_PATH = Path("inputs/house_manual_polls.csv")

st.set_page_config(page_title="House Manual Poll Editor", layout="wide")

st.title("House Manual Poll Editor")
st.caption(
    "Add, edit, or delete manually entered House polls. Partisan/sponsor metadata "
    "feeds the House partisan pollster adjustment script. Manual house-effect fields "
    "are not exposed here; poll adjustments are generated by the pipeline."
)

if not POLL_PATH.exists():
    st.error(f"Could not find {POLL_PATH}")
    st.stop()


def clean_text_series(s):
    return (
        s.fillna("")
        .astype(str)
        .replace({"nan": "", "None": "", "NaN": ""})
    )


df = pd.read_csv(POLL_PATH)

# Core fields commonly used by the House manual poll file.
# This editor keeps any existing legitimate columns but removes generated/audit columns.
generated_or_audit_cols = {
    "polling_margin_dem_original",
    "partisan_pollster_adjustment_dem",
    "partisan_pollster_weight_multiplier",
    "partisan_pollster_adjusted",
    "partisan_pollster_notes",
    "polling_margin_dem_adjusted",
    "margin_dem",
    "final_poll_margin_dem",
    "house_effect_adjusted_dem_margin",
    "house_effect_dem",
    "house_effect_adjustment_dem",
    "manual_house_effect",
    "manual_house_effect_adjustment_dem",
}

df = df.drop(columns=[c for c in generated_or_audit_cols if c in df.columns], errors="ignore")

metadata_defaults = {
    "poll_sponsor_type": "",
    "partisan_sponsor_party": "",
    "is_internal_poll": False,
    "pollster_partisan_affiliation": "",
    "partisan_pollster_review_notes": "",
}

for col, default in metadata_defaults.items():
    if col not in df.columns:
        df[col] = default

# Normalize metadata fields.
for col in [
    "poll_sponsor_type",
    "partisan_sponsor_party",
    "pollster_partisan_affiliation",
    "partisan_pollster_review_notes",
]:
    df[col] = clean_text_series(df[col])

df["is_internal_poll"] = (
    df["is_internal_poll"]
    .fillna(False)
    .astype(str)
    .str.lower()
    .isin(["true", "1", "yes", "y"])
)

# Build a friendly column order while preserving any existing House-specific columns.
preferred_front = [
    "district_id",
    "district",
    "race",
    "state",
    "pollster",
    "pollster_grade",
    "sponsor",
    "poll_sponsor_type",
    "partisan_sponsor_party",
    "is_internal_poll",
    "pollster_partisan_affiliation",
    "partisan_pollster_review_notes",
    "start_date",
    "end_date",
    "sample_size",
    "population",
    "sample_type",
    "mode",
    "dem_candidate",
    "gop_candidate",
    "rep_candidate",
    "dem_pct",
    "gop_pct",
    "rep_pct",
    "ind_pct",
    "other_pct",
    "undecided_pct",
    "notes",
]

ordered_cols = [c for c in preferred_front if c in df.columns]
remaining_cols = [c for c in df.columns if c not in ordered_cols]
df = df.loc[:, ordered_cols + remaining_cols].copy()

# Normalize likely text columns.
for col in df.columns:
    if col not in [
        "sample_size",
        "dem_pct",
        "gop_pct",
        "rep_pct",
        "ind_pct",
        "other_pct",
        "undecided_pct",
        "is_internal_poll",
    ]:
        if df[col].dtype == object:
            df[col] = clean_text_series(df[col])

# Numeric conversion for common numeric fields.
for col in [
    "sample_size",
    "dem_pct",
    "gop_pct",
    "rep_pct",
    "ind_pct",
    "other_pct",
    "undecided_pct",
]:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors="coerce")

st.markdown("### Edit Existing Manual Polls")

st.caption(
    "Use the table below to edit existing polls. To delete a poll, check Delete "
    "and then click Save Edits / Delete Marked Polls."
)

editable = df.copy()
editable.insert(0, "delete", False)
editable.insert(1, "row_id", range(1, len(editable) + 1))

edited = st.data_editor(
    editable,
    use_container_width=True,
    hide_index=True,
    num_rows="fixed",
    key="house_manual_poll_editor_unified_v1",
    column_config={
        "delete": st.column_config.CheckboxColumn("Delete", default=False),
        "row_id": st.column_config.NumberColumn("Row", disabled=True),
        "pollster_grade": st.column_config.SelectboxColumn(
            "Pollster grade",
            options=["A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D", "Unknown", ""],
        ),
        "population": st.column_config.SelectboxColumn(
            "Population",
            options=["LV", "RV", "A", "Other", ""],
        ),
        "sample_type": st.column_config.SelectboxColumn(
            "Sample type",
            options=["LV", "RV", "A", "Other", ""],
        ),
        "poll_sponsor_type": st.column_config.SelectboxColumn(
            "Sponsor type",
            options=["", "independent", "media", "university", "party", "campaign", "super PAC", "other"],
        ),
        "partisan_sponsor_party": st.column_config.SelectboxColumn(
            "Sponsor party",
            options=["", "D", "R", "none", "unknown"],
        ),
        "is_internal_poll": st.column_config.CheckboxColumn(
            "Internal/campaign poll",
            default=False,
        ),
        "pollster_partisan_affiliation": st.column_config.SelectboxColumn(
            "Pollster partisan affiliation",
            options=["", "D", "R", "none", "unknown"],
        ),
        "partisan_pollster_review_notes": st.column_config.TextColumn(
            "Partisan poll notes",
        ),
        "sample_size": st.column_config.NumberColumn(
            "Sample size",
            min_value=0,
            step=1,
            format="%d",
        ),
        "dem_pct": st.column_config.NumberColumn("Dem %", step=0.1, format="%.1f"),
        "gop_pct": st.column_config.NumberColumn("GOP %", step=0.1, format="%.1f"),
        "rep_pct": st.column_config.NumberColumn("Rep %", step=0.1, format="%.1f"),
        "ind_pct": st.column_config.NumberColumn("Ind %", step=0.1, format="%.1f"),
        "other_pct": st.column_config.NumberColumn("Other %", step=0.1, format="%.1f"),
        "undecided_pct": st.column_config.NumberColumn("Undecided %", step=0.1, format="%.1f"),
    },
)

c_save, c_info = st.columns([1, 3])

with c_save:
    save_edits = st.button("Save Edits / Delete Marked Polls", type="primary")

with c_info:
    st.caption("Saving overwrites inputs/house_manual_polls.csv and creates a .bak backup.")

if save_edits:
    updated = edited.copy()

    if "delete" in updated.columns:
        updated = updated[~updated["delete"].fillna(False)].copy()

    for col in ["delete", "row_id"]:
        if col in updated.columns:
            updated = updated.drop(columns=[col])

    # Preserve original editor order.
    updated = updated.loc[:, [c for c in df.columns if c in updated.columns]].copy()

    for col in [
        "poll_sponsor_type",
        "partisan_sponsor_party",
        "pollster_partisan_affiliation",
        "partisan_pollster_review_notes",
    ]:
        if col in updated.columns:
            updated[col] = clean_text_series(updated[col])

    if "is_internal_poll" in updated.columns:
        updated["is_internal_poll"] = (
            updated["is_internal_poll"]
            .fillna(False)
            .astype(str)
            .str.lower()
            .isin(["true", "1", "yes", "y"])
        )

    for col in [
        "sample_size",
        "dem_pct",
        "gop_pct",
        "rep_pct",
        "ind_pct",
        "other_pct",
        "undecided_pct",
    ]:
        if col in updated.columns:
            updated[col] = pd.to_numeric(updated[col], errors="coerce")

    # Drop fully blank rows.
    key_cols = [c for c in ["district_id", "district", "race", "pollster", "dem_pct", "gop_pct", "rep_pct"] if c in updated.columns]
    if key_cols:
        nonblank_mask = updated[key_cols].notna().any(axis=1)
        updated = updated[nonblank_mask].copy()

    POLL_PATH.parent.mkdir(parents=True, exist_ok=True)

    if POLL_PATH.exists():
        backup_path = POLL_PATH.with_suffix(".csv.bak")
        df.to_csv(backup_path, index=False)

    updated.to_csv(POLL_PATH, index=False)

    st.success(f"Saved {len(updated)} manual polls to {POLL_PATH}. Run the House full pipeline to ingest the changes.")

st.divider()

st.markdown("### Add New Poll")

# Choose field names based on current file schema.
district_field = "district_id" if "district_id" in df.columns else "district" if "district" in df.columns else "race"
gop_pct_field = "gop_pct" if "gop_pct" in df.columns else "rep_pct"

with st.form("house_manual_poll_entry_form_unified_v1"):
    c1, c2, c3 = st.columns(3)

    with c1:
        district_value = st.text_input("District / Race", value="")
        state = st.text_input("State", value="")
        pollster = st.text_input("Pollster", value="")
        pollster_grade = st.selectbox(
            "Pollster grade",
            ["A+", "A", "A-", "B+", "B", "B-", "C+", "C", "C-", "D", "Unknown", ""],
            index=4,
        )
        sponsor = st.text_input("Sponsor", value="")

    with c2:
        start_date = st.date_input("Start date")
        end_date = st.date_input("End date")
        sample_size = st.number_input("Sample size", min_value=0, value=800, step=1)
        sample_type = st.selectbox("Sample type", ["LV", "RV", "A", "Other", ""], index=0)
        dem_candidate = st.text_input("Dem candidate", value="")
        gop_candidate = st.text_input("GOP/Rep candidate", value="")

    with c3:
        dem_pct = st.number_input("Dem %", value=0.0, step=0.1, format="%.1f")
        gop_pct = st.number_input("GOP/Rep %", value=0.0, step=0.1, format="%.1f")
        ind_pct = st.number_input("Ind %", value=0.0, step=0.1, format="%.1f")
        other_pct = st.number_input("Other %", value=0.0, step=0.1, format="%.1f")
        undecided_pct = st.number_input("Undecided %", value=0.0, step=0.1, format="%.1f")
        notes = st.text_area("General notes", value="")

    st.markdown("#### Partisan / Sponsor Metadata")

    p1, p2, p3 = st.columns(3)

    with p1:
        poll_sponsor_type = st.selectbox(
            "Sponsor type",
            ["", "independent", "media", "university", "party", "campaign", "super PAC", "other"],
            index=0,
        )

    with p2:
        partisan_sponsor_party = st.selectbox(
            "Sponsor party",
            ["", "D", "R", "none", "unknown"],
            index=0,
        )

    with p3:
        pollster_partisan_affiliation = st.selectbox(
            "Pollster partisan affiliation",
            ["", "D", "R", "none", "unknown"],
            index=0,
        )

    is_internal_poll = st.checkbox("Internal/campaign poll", value=False)
    partisan_pollster_review_notes = st.text_input("Partisan poll notes", value="")

    submitted = st.form_submit_button("Add Poll")

    if submitted:
        new_row = {c: "" for c in df.columns}

        new_row[district_field] = district_value
        if "state" in new_row:
            new_row["state"] = state.strip().upper()
        if "pollster" in new_row:
            new_row["pollster"] = pollster
        if "pollster_grade" in new_row:
            new_row["pollster_grade"] = pollster_grade
        if "sponsor" in new_row:
            new_row["sponsor"] = sponsor
        if "start_date" in new_row:
            new_row["start_date"] = start_date.isoformat()
        if "end_date" in new_row:
            new_row["end_date"] = end_date.isoformat()
        if "sample_size" in new_row:
            new_row["sample_size"] = sample_size
        if "sample_type" in new_row:
            new_row["sample_type"] = sample_type
        if "population" in new_row:
            new_row["population"] = sample_type
        if "dem_candidate" in new_row:
            new_row["dem_candidate"] = dem_candidate
        if "gop_candidate" in new_row:
            new_row["gop_candidate"] = gop_candidate
        if "rep_candidate" in new_row:
            new_row["rep_candidate"] = gop_candidate

        new_row["dem_pct"] = dem_pct
        new_row[gop_pct_field] = gop_pct

        if "ind_pct" in new_row:
            new_row["ind_pct"] = ind_pct
        if "other_pct" in new_row:
            new_row["other_pct"] = other_pct
        if "undecided_pct" in new_row:
            new_row["undecided_pct"] = undecided_pct
        if "notes" in new_row:
            new_row["notes"] = notes

        new_row["poll_sponsor_type"] = poll_sponsor_type
        new_row["partisan_sponsor_party"] = partisan_sponsor_party
        new_row["is_internal_poll"] = is_internal_poll
        new_row["pollster_partisan_affiliation"] = pollster_partisan_affiliation
        new_row["partisan_pollster_review_notes"] = partisan_pollster_review_notes

        updated = pd.concat([df, pd.DataFrame([new_row])], ignore_index=True)
        updated.to_csv(POLL_PATH, index=False)

        st.success(f"Saved new poll to {POLL_PATH}. Run the House full pipeline to ingest it.")
        st.dataframe(updated.tail(10), use_container_width=True, hide_index=True)

st.divider()

st.markdown("### How to use partisan fields")

st.write(
    """
    - Public/media poll: leave sponsor party blank or use `none`; internal unchecked.
    - Democratic internal: sponsor type `campaign`, sponsor party `D`, internal checked.
    - Republican internal: sponsor type `campaign`, sponsor party `R`, internal checked.
    - Known partisan pollster but not sponsored: use pollster partisan affiliation `D` or `R`; sponsor party can stay blank or `none`.
    """
)
